export const S = {
  eyebrow: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 10,
    color: '#6b2d5c',
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
  },
  hero: {
    fontFamily: "'Instrument Serif', serif",
    fontSize: 72,
    lineHeight: 1.02,
    fontWeight: 400,
    margin: '14px 0 0',
    letterSpacing: '-0.015em',
    color: '#f4d9e4',
    textWrap: 'pretty',
  },
  tag: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 10,
    color: '#d4a5c4',
    background: 'rgba(212,165,196,0.06)',
    border: '1px solid #3a2a4a',
    padding: '4px 9px',
    letterSpacing: '0.05em',
  },
  miniTag: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 9,
    color: '#8a7a9a',
    padding: '2px 6px',
    border: '1px solid #3a2a4a',
  },
  link: { color: '#d4a5c4', textDecoration: 'none', borderBottom: '1px solid #6b2d5c' },
  ctaBtn: {
    marginTop: 32,
    background: 'none',
    border: '1px solid #6b2d5c',
    color: '#f4d9e4',
    padding: '14px 20px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 12,
    letterSpacing: '0.1em',
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    textTransform: 'uppercase',
    transition: 'background .2s',
  },
  projectGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: 1,
    background: '#3a2a4a',
    border: '1px solid #3a2a4a',
  },
  card: (hover) => ({
    background: hover ? '#1a1230' : '#0e0b1a',
    textAlign: 'left',
    border: 'none',
    padding: 28,
    cursor: 'pointer',
    color: 'inherit',
    fontFamily: 'inherit',
    transition: 'background .4s ease',
    minHeight: 220,
    display: 'flex',
    flexDirection: 'column',
  }),
  photoLabel: {
    position: 'absolute',
    top: 8,
    left: 8,
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 9,
    color: '#8a7a9a',
    letterSpacing: '0.1em',
    zIndex: 2,
  },
}

export const PROJECTS = [
  {
    id: 'returns',
    num: '01',
    title: 'Return-Forecasting Pipeline',
    kicker: 'Empover i-Tech · Data Science Intern',
    year: '2025',
    tags: ['LightGBM', 'XGBoost', 'Power BI', 'SQL'],
    stat: 'R² 0.67',
    statLabel: 'across 50K+ SKUs',
    oneline: 'Forecasting returns across 2,000+ distributors, turning model output into inventory decisions.',
    body: [
      'Engineered 32 lag-based temporal and sales features from 3 years of distributor data across 18+ regions.',
      'Selected the best model across 4 regression algorithms via RandomizedSearchCV. LightGBM won at R² = 0.67.',
      'Shipped a Power BI dashboard surfacing top return drivers by SKU, distributor, and region. Used directly by inventory planners to allocate stock.',
      'Refactored 5 fragmented notebooks into 25 reusable parameterised pipeline functions — 89% codebase reduction.',
    ],
    repo: 'https://github.com/anushkamohanty14',
  },
  {
    id: 'truehire',
    num: '02',
    title: 'TrueHire',
    kicker: 'AI-Powered Career Intelligence',
    year: '2025',
    tags: ['FastAPI', 'scikit-learn', 'SciPy', 'MongoDB'],
    stat: '894 jobs',
    statLabel: 'O*NET occupation coverage',
    oneline: 'A 3-signal hybrid scoring engine for personalised career recommendations.',
    body: [
      'Cosine similarity for cognitive fit (40%), dot-product for work-activity matching (30%), Jaccard for tech-skill overlap (30%).',
      'Quantified cognitive readiness across 9 ability domains — accuracy (70%) × reaction time (30%), mapped to population percentiles via empirical CDF.',
      'Architected a clean 4-layer system (browser → API → ML pipeline → data store) with 13+ REST endpoints and sub-3s latency SLAs.',
    ],
    repo: 'https://github.com/anushkamohanty14',
  },
  {
    id: 'fakenews',
    num: '03',
    title: 'Fake News Spread Simulator',
    kicker: 'Research · submitted to COMSNETS & ICDCN 2026',
    year: '2025',
    tags: ['NetworkX', 'FastAPI', 'Monte Carlo', 'vis-network.js'],
    stat: '52.3 pp',
    statLabel: 'peak misinformation reduction',
    oneline: 'A five-state probabilistic diffusion framework with non-Markovian forwarding limits.',
    body: [
      'Designed the core model: five-state probabilistic diffusion with cumulative node-level forwarding constraints.',
      'Validated across Erdős–Rényi, Watts–Strogatz, and Barabási–Albert topologies with 50-run Monte Carlo.',
      'Topology-dependent finding: forwarding limits cut peak misinformation 26.5 pp in random networks, 0.7 pp in small-world; fact-checkers most effective in scale-free networks (−25.6 pp via hub firebreaks).',
    ],
    repo: 'https://github.com/anushkamohanty14',
  },
  {
    id: 'skin',
    num: '04',
    title: 'Multimodal Skin Lesion Classification',
    kicker: 'HAM10000 · PyTorch',
    year: '2024',
    tags: ['Swin Transformer', 'PubMedBERT', 'Gated Fusion', 'Focal Loss'],
    stat: '+6.7 pp',
    statLabel: 'Macro-F1 over vision-only',
    oneline: 'Fusing Swin Transformer with PubMedBERT via a gated fusion network.',
    body: [
      'Fused fine-tuned Swin Transformer (images) with PubMedBERT (clinical metadata) via a gated fusion network.',
      '91.02% accuracy across 3 independent runs, Sparse Focal Loss (γ=2.0) handling 7-class imbalance.',
      'Ablation: Swin-only F1 0.750, PubMedBERT-only 0.720, fusion 0.817 — confirmed complementary visual and clinical signals.',
    ],
    repo: 'https://github.com/anushkamohanty14',
  },
  {
    id: 'daira',
    num: '05',
    title: 'Pediatric Medical AI Reasoning Layer',
    kicker: "Daira EdTech · Founder's Office",
    year: '2026',
    tags: ['Neo4j', 'MedGemma', 'Gemini 2.5 Flash', 'RAG'],
    stat: '16 × 18',
    statLabel: 'entities × relationships',
    oneline: 'A knowledge-graph RAG source for a pediatric chatbot spanning 0–6 years of development.',
    body: [
      'Architected a 16-entity, 18-relationship Neo4j schema mapping developmental milestones, red flags, growth parameters, vaccines, and interventions.',
      'Used directly as the structured RAG source for a MedGemma + Gemini 2.5 Flash pipeline.',
      'Scraped and analysed online forum data, quantifying 6 concern-intent categories to ground feature prioritisation in real parental behaviour.',
    ],
    repo: null,
  },
  {
    id: 'cogload',
    num: '06',
    title: 'Cognitive Load in UX & AI',
    kicker: 'Undergraduate Research · presented at ISRC Istanbul',
    year: '2024',
    tags: ['PsychoPy', 'Behavioural Experimentation', 'A/B'],
    stat: '−19%',
    statLabel: 'task completion time (n=120)',
    oneline: 'Identifying menu navigation as the primary friction point in AI interfaces.',
    body: [
      'Controlled PsychoPy experiments across 3 interface variants, collecting 2,000+ behavioural signals from n=120.',
      'Found menu navigation caused 34% of user hesitation — the single largest friction source.',
      'Reduced task completion time by 19% in the redesigned variant.',
    ],
    repo: null,
  },
]
